import React, { useState, useEffect, Fragment } from "react";
import { Bar } from "react-chartjs-2";
import { amortSchedCA } from "../../../scripts/amortCA";
import addMonths from "date-fns/addMonths";

function LoanExpiriesPerYearChart() {
  const sampleData = [
    {
      id: 433,
      user_id: 1,
      Asset_Owner: "Canada Post",
      Asset_Manager: "Morguard",
      Borrowing_Entity_Registered_on_Title: "123 Main Street Holdco Inc. ",
      Property_Name: "Main Street ",
      Address: "123 Main Street ",
      Postal: "",
      City: "Toronto",
      Province: "ON",
      Country: "ca",
      Purchase_Price: "2000000.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 17500,
      Lender: "",
      Lender_Classification: "Life Co.",
      Original_Loan_Amount: "2000000.00",
      First_Payment_Date: "January 31 2015",
      Term: 60,
      Amortization: 300,
      Fixed_Variable: "Variable",
      BOC_Prime: "2.75",
      GOC_Prime: "0.25",
      Variable_Spread: "2.50",
      Fixed_Rate: "2.75",
      Pre_Payment_Penalty_Type: "3-Month Interest ",
      Recent_Appraisal_Date: "January 30 2015",
      Recent_Appraisal_Cap_Rate: "6.00",
      Recent_Appraisal_Value: "3340000.00",
      Internal_Valuation_Date: "August 31 2015",
      Internal_Valuation_Cap: "5.75",
      Internal_Valuation_NOI: "200250.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "October 1 2004",
      Notes: null,
      loaded_from: null
    },
    {
      id: 434,
      user_id: 1,
      Asset_Owner: "Hydro Quebec",
      Asset_Manager: "Triovest",
      Borrowing_Entity_Registered_on_Title: "ACI Brandon Dennis Ltd.",
      Property_Name: "Shoppers - Brandon",
      Address: "",
      Postal: "1",
      City: "Brandon",
      Province: "MB",
      Country: "ca",
      Purchase_Price: "10000000.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 17000,
      Lender: "",
      Lender_Classification: "CMBS / Conduits",
      Original_Loan_Amount: "14000000.00",
      First_Payment_Date: "April 1 2011",
      Term: 120,
      Amortization: 176,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "5.90",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "April 30 2014",
      Recent_Appraisal_Cap_Rate: "6.00",
      Recent_Appraisal_Value: "26200000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "5.75",
      Internal_Valuation_NOI: "1000000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 11 2011",
      Notes: null,
      loaded_from: null
    },

    {
      id: 435,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "ACI Shoppers Southpark Ltd.",
      Property_Name: "Shoppers - Pembina",
      Address: "",
      Postal: "",
      City: "Pembina",
      Province: "MB",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 15780,
      Lender: "Montrose Mortgage Fund",
      Lender_Classification: "CMBS / Conduits",
      Original_Loan_Amount: "2995000.00",
      First_Payment_Date: "may 22 2011",
      Term: 120,
      Amortization: 158,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "6.70",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "",
      Recent_Appraisal_Cap_Rate: "6.00",
      Recent_Appraisal_Value: "6700000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "402000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "February 23, 2017",
      Notes: null,
      loaded_from: null
    },
    {
      id: 436,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "ACI Selkirk Ltd.",
      Property_Name: "Shoppers - Selkirk",
      Address: "",
      Postal: "",
      City: "Selkirk",
      Province: "MB",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 16685,
      Lender: "CMLS",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "2425000.00",
      First_Payment_Date: "April 1 2011",
      Term: 120,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "6.35",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "April 30 2014",
      Recent_Appraisal_Cap_Rate: "6.25",
      Recent_Appraisal_Value: "4800000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "300000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 11 2011",
      Notes: null,
      loaded_from: null
    },
    {
      id: 437,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Somerset Corner Ltd.",
      Property_Name: "Shoppers - Sherbrook",
      Address: "",
      Postal: "",
      City: "Sherbrook",
      Province: "MB",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "Class B",
      Size: 16839,
      Lender: "Bmo",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "38000.00",
      First_Payment_Date: "March 1 2011",
      Term: 118,
      Amortization: 238,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "6.07",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "April 30 2014",
      Recent_Appraisal_Cap_Rate: "6.00",
      Recent_Appraisal_Value: "7000000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "5.75",
      Internal_Valuation_NOI: "420000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 11 2011",
      Notes: null,
      loaded_from: null
    },
    {
      id: 438,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "S.D.A. Steinbach Ltd.",
      Property_Name: "Shoppers - Steinbach",
      Address: "",
      Postal: "",
      City: "Steinbach",
      Province: "MB",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 21005,
      Lender: "CMLS",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "13025000.00",
      First_Payment_Date: "March 1 2011",
      Term: 124,
      Amortization: 165,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "5.76",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "April 30 2014",
      Recent_Appraisal_Cap_Rate: "6.25",
      Recent_Appraisal_Value: "16600000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "4125000.02",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 11 2011",
      Notes: null,
      loaded_from: null
    },

    {
      id: 439,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "RMA Gatineau Ltd.",
      Property_Name: "Shoppers - Gatineau",
      Address: "",
      Postal: "",
      City: "Gatineau",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 17028,
      Lender: "First National Financial",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "4050000.00",
      First_Payment_Date: "April 1 2011",
      Term: 120,
      Amortization: 251,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "5.93",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "April 30 2014",
      Recent_Appraisal_Cap_Rate: "6.25",
      Recent_Appraisal_Value: "6400000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "400000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 17 2011",
      Notes: null,
      loaded_from: null
    },
    {
      id: 440,
      user_id: 1,
      Asset_Owner: "AIMCo",
      Asset_Manager: "Bentall",
      Borrowing_Entity_Registered_on_Title: "Cobblestone SC",
      Property_Name: "Prairie Mall Shopping Centre",
      Address: "11801-100th Street",
      Postal: "",
      City: "Grand Prairie",
      Province: "AB",
      Country: "ca",
      Purchase_Price: "13000000.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 198000,
      Lender: "CMLS",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "11000000.00",
      First_Payment_Date: "September 1 2013",
      Term: 120,
      Amortization: 173,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "2.01",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2016",
      Recent_Appraisal_Cap_Rate: "6.25",
      Recent_Appraisal_Value: "16800000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "1050000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "August 22 2013",
      Notes: null,
      loaded_from: null
    },
    {
      id: 441,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Wellington Southdale",
      Property_Name: "Wellington Southdale",
      Address: "",
      Postal: "",
      City: "London",
      Province: "ON",
      Country: "ca",
      Purchase_Price: "150000000.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 855624,
      Lender: "Manulife",
      Lender_Classification: "Life Co.",
      Original_Loan_Amount: "121220000.00",
      First_Payment_Date: "January 1 2011",
      Term: 67,
      Amortization: 490,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "2.00",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2013",
      Recent_Appraisal_Cap_Rate: "6.50",
      Recent_Appraisal_Value: "194600000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.25",
      Internal_Valuation_NOI: "1599000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "December 22 2010",
      Notes: null,
      loaded_from: null
    },
    {
      id: 442,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "137th Avenue GP Inc.",
      Property_Name: "137th Avenue",
      Address: "",
      Postal: "",
      City: "Edmonton",
      Province: "AB",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 15922,
      Lender: "MCAP",
      Lender_Classification: "CMBS / Conduits",
      Original_Loan_Amount: "2550000.00",
      First_Payment_Date: "February 1 2012",
      Term: 60,
      Amortization: 340,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "2.23",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2015",
      Recent_Appraisal_Cap_Rate: "5.75",
      Recent_Appraisal_Value: "4900000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "5.50",
      Internal_Valuation_NOI: "281750.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "December 19 2011",
      Notes: null,
      loaded_from: null
    },
    {
      id: 443,
      user_id: 1,
      Asset_Owner: "ABC Hold Co.",
      Asset_Manager: "Bentall Kennedy",
      Borrowing_Entity_Registered_on_Title: "Manning Crossing Holdings Inc.",
      Property_Name: "Manning Crossing",
      Address: "",
      Postal: "",
      City: "Edmonton",
      Province: "AB",
      Country: "ca",
      Purchase_Price: "20000000.00",
      Asset_Type: "Industrial",
      Asset_Class: "Class A",
      Size: 64528,
      Lender: "",
      Lender_Classification: "Life Co.",
      Original_Loan_Amount: "15250000.00",
      First_Payment_Date: "December 1 2014",
      Term: 60,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "4.21",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "September 29 2014",
      Recent_Appraisal_Cap_Rate: "6.50",
      Recent_Appraisal_Value: "23100000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.25",
      Internal_Valuation_NOI: "1501500.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "February 14 2012",
      Notes: null,
      loaded_from: null
    },
    {
      id: 444,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Evergreen Centre Holdings Corp.",
      Property_Name: "Evergreen SC",
      Address: "",
      Postal: "",
      City: "Sooke",
      Province: "BC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 72105,
      Lender: "Coast Capital Savings Credit Union",
      Lender_Classification: "Credit Union or Trust Co.",
      Original_Loan_Amount: "10500000.00",
      First_Payment_Date: "September 1 2011",
      Term: 60,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "3.80",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2014",
      Recent_Appraisal_Cap_Rate: "6.50",
      Recent_Appraisal_Value: "17200000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.25",
      Internal_Valuation_NOI: "1118000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "September 1 2011",
      Notes: null,
      loaded_from: null
    },
    {
      id: 445,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Washington Park Holdings Corp.",
      Property_Name: "Washington Park SC",
      Address: "",
      Postal: "",
      City: "Courtenay",
      Province: "BC",
      Country: "ca",
      Purchase_Price: "25000000.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 32603,
      Lender: "",
      Lender_Classification: "Credit Union or Trust Co.",
      Original_Loan_Amount: "17500000.00",
      First_Payment_Date: "June 1 2012",
      Term: 60,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "3.84",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2015",
      Recent_Appraisal_Cap_Rate: "6.50",
      Recent_Appraisal_Value: "25000000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.25",
      Internal_Valuation_NOI: "741000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "June 15 2012",
      Notes: null,
      loaded_from: null
    },
    {
      id: 446,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Mariner Holdings Ltd.",
      Property_Name: "Mariner Square SC",
      Address: "",
      Postal: "",
      City: "Campbell River",
      Province: "BC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 100257,
      Lender: "Sunlife",
      Lender_Classification: "Life Co.",
      Original_Loan_Amount: "18250000.00",
      First_Payment_Date: "May 1 2013",
      Term: 55,
      Amortization: 235,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "5.74",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2013",
      Recent_Appraisal_Cap_Rate: "6.25",
      Recent_Appraisal_Value: "27200000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "1700000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "April 15 2013",
      Notes: null,
      loaded_from: null
    },
    {
      id: 447,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title:
        "Centuria Urban Village Holdings Corp.",
      Property_Name: "Centuria Urban Village",
      Address: "",
      Postal: "",
      City: "Kelowna",
      Province: "BC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 32625,
      Lender: "",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "47250000.00",
      First_Payment_Date: "December 1 2014",
      Term: 120,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "4.21",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "October 1 2014",
      Recent_Appraisal_Cap_Rate: "6.50",
      Recent_Appraisal_Value: "10600000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.25",
      Internal_Valuation_NOI: "689000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "May 16 2011",
      Notes: null,
      loaded_from: null
    },
    {
      id: 448,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Charter Acquisition Corp.",
      Property_Name: "Cornwall Square",
      Address: "",
      Postal: "",
      City: "Cornwall",
      Province: "ON",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 825092,
      Lender: "Alterna",
      Lender_Classification: "Credit Union or Trust Co.",
      Original_Loan_Amount: "55500000.00",
      First_Payment_Date: "December 1 2010",
      Term: 60,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "4.90",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2015",
      Recent_Appraisal_Cap_Rate: "7.75",
      Recent_Appraisal_Value: "33600000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "7.50",
      Internal_Valuation_NOI: "2604000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "August 2 2007",
      Notes: null,
      loaded_from: null
    },
    {
      id: 449,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title:
        "Grand Bend Town Centre Holdings Inc.",
      Property_Name: "Grand Bend TC",
      Address: "",
      Postal: "",
      City: "Grand Bend",
      Province: "ON",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 41605,
      Lender: "CIBC",
      Lender_Classification: "Canadian Bank",
      Original_Loan_Amount: "4000000.00",
      First_Payment_Date: "June 1 2012",
      Term: 62,
      Amortization: 240,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "5.12",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2014",
      Recent_Appraisal_Cap_Rate: "7.00",
      Recent_Appraisal_Value: "9200000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.75",
      Internal_Valuation_NOI: "644000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "April 30 2012",
      Notes: null,
      loaded_from: null
    },
    {
      id: 450,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title:
        "St. Clair Beach Town Centre Holdings Inc.",
      Property_Name: "St. Clair Beach TC",
      Address: "1 Main Street",
      Postal: "",
      City: "Windsor",
      Province: "ON",
      Country: "ca",
      Purchase_Price: "15000000.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 40088,
      Lender: "CIBC",
      Lender_Classification: "Canadian Bank",
      Original_Loan_Amount: "16250000.00",
      First_Payment_Date: "April 1 2012",
      Term: 64,
      Amortization: 240,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "4.60",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2015",
      Recent_Appraisal_Cap_Rate: "7.00",
      Recent_Appraisal_Value: "18100000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.75",
      Internal_Valuation_NOI: "847000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "February 14 2012",
      Notes: null,
      loaded_from: null
    },
    {
      id: 451,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Thunder Centre Holdings Inc.",
      Property_Name: "Thunder Power Centre",
      Address: "1 main street",
      Postal: "",
      City: "Thunder Bay",
      Province: "ON",
      Country: "ca",
      Purchase_Price: "23300033.33",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 168087,
      Lender: "CIBC",
      Lender_Classification: "Canadian Bank",
      Original_Loan_Amount: "19500000.00",
      First_Payment_Date: "April 1 2012",
      Term: 64,
      Amortization: 240,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "4.78",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2015",
      Recent_Appraisal_Cap_Rate: "6.25",
      Recent_Appraisal_Value: "40700000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "12543750.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "February 14 2014",
      Notes: null,
      loaded_from: null
    },
    {
      id: 452,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Timmins Holdings Inc",
      Property_Name: "Timmins West PC",
      Address: "",
      Postal: "",
      City: "Timmins",
      Province: "ON",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 43774,
      Lender: "CIBC",
      Lender_Classification: "Canadian Bank",
      Original_Loan_Amount: "5400000.00",
      First_Payment_Date: "January 1 2013",
      Term: 69,
      Amortization: 249,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "6.00",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "November 1 2012",
      Recent_Appraisal_Cap_Rate: "7.25",
      Recent_Appraisal_Value: "10300000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "7.00",
      Internal_Valuation_NOI: "746750.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "December 20 2012",
      Notes: null,
      loaded_from: null
    },
    {
      id: 453,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Quinte Centre Holdings Inc.",
      Property_Name: "Quinte Crossroads",
      Address: "",
      Postal: "",
      City: "Belleville",
      Province: "ON",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 85200,
      Lender: "",
      Lender_Classification: "Foreign Lender",
      Original_Loan_Amount: "14200000.00",
      First_Payment_Date: "May 1 2012",
      Term: 120,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "4.06",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2014",
      Recent_Appraisal_Cap_Rate: "6.75",
      Recent_Appraisal_Value: "21600000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.50",
      Internal_Valuation_NOI: "1458000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 31 2012",
      Notes: null,
      loaded_from: null
    },
    {
      id: 454,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Charter Acquisition Corp.",
      Property_Name: "Place Val Est (PVE)",
      Address: "",
      Postal: "",
      City: "Sudbury",
      Province: "ON",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 110577,
      Lender: "RBC",
      Lender_Classification: "Canadian Bank",
      Original_Loan_Amount: "8500000.00",
      First_Payment_Date: "November 1 2005",
      Term: 120,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "5.17",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2012",
      Recent_Appraisal_Cap_Rate: "7.75",
      Recent_Appraisal_Value: "13000000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "7.50",
      Internal_Valuation_NOI: "1007500.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "January 31 2008",
      Notes: null,
      loaded_from: null
    },
    {
      id: 455,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "King George Square Holdings Inc.",
      Property_Name: "King George Square",
      Address: "",
      Postal: "",
      City: "Brantford",
      Province: "ON",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 66983,
      Lender: "First National Financial",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "12250000.00",
      First_Payment_Date: "January 1 2015",
      Term: 60,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "3.41",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "September 30 2014",
      Recent_Appraisal_Cap_Rate: "6.75",
      Recent_Appraisal_Value: "17000000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.50",
      Internal_Valuation_NOI: "1147500.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "February 14 2012",
      Notes: null,
      loaded_from: null
    },
    {
      id: 456,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Crossing Bridge Holdings Inc.",
      Property_Name: "Crossing Bridge Square",
      Address: "",
      Postal: "",
      City: "Stittsville",
      Province: "ON",
      Country: "ca",
      Purchase_Price: "55555555.55",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 45913,
      Lender: "",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "38000000.00",
      First_Payment_Date: "January 1 2015",
      Term: 60,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "3.41",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "July 1 2014",
      Recent_Appraisal_Cap_Rate: "6.25",
      Recent_Appraisal_Value: "42600000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "1787500.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "February 14 2012",
      Notes: null,
      loaded_from: null
    },
    {
      id: 457,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Charter Realty (Quebec) Corp.",
      Property_Name: "Chateauguay",
      Address: "",
      Postal: "",
      City: "Montreal",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 115209,
      Lender: "CIBC",
      Lender_Classification: "Canadian Bank",
      Original_Loan_Amount: "11000000.00",
      First_Payment_Date: "December 1 2011",
      Term: 60,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "3.42",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2015",
      Recent_Appraisal_Cap_Rate: "7.25",
      Recent_Appraisal_Value: "16300000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "7.00",
      Internal_Valuation_NOI: "1181750.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "November 30 2207",
      Notes: null,
      loaded_from: null
    },
    {
      id: 458,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "1124 Iberville Inc.",
      Property_Name: "Repentigny SC",
      Address: "",
      Postal: "",
      City: "Repentigny",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 49371,
      Lender: "National Bank",
      Lender_Classification: "Canadian Bank",
      Original_Loan_Amount: "5650000.00",
      First_Payment_Date: "May 1 2013",
      Term: 60,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "3.34",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2015",
      Recent_Appraisal_Cap_Rate: "7.50",
      Recent_Appraisal_Value: "8000000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "7.25",
      Internal_Valuation_NOI: "600000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "May 1 2013",
      Notes: null,
      loaded_from: null
    },
    {
      id: 459,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "340-356 Poliquin Inc ",
      Property_Name: "Sorel SC",
      Address: "",
      Postal: "",
      City: "Sorel (Mtl)",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 31038,
      Lender: "National Bank",
      Lender_Classification: "Canadian Bank",
      Original_Loan_Amount: "4200000.00",
      First_Payment_Date: "April 1 2013",
      Term: 84,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "3.70",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "March 1 2013",
      Recent_Appraisal_Cap_Rate: "6.50",
      Recent_Appraisal_Value: "9300000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.25",
      Internal_Valuation_NOI: "604500.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 15 2013",
      Notes: null,
      loaded_from: null
    },
    {
      id: 460,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "810 Saint-Paul Inc.",
      Property_Name: "St. Remi SC",
      Address: "",
      Postal: "",
      City: "St. Remi (Mtl)",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 61704,
      Lender: "National Bank",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "11550000.00",
      First_Payment_Date: "April 1 2013",
      Term: 84,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "3.72",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2015",
      Recent_Appraisal_Cap_Rate: "7.00",
      Recent_Appraisal_Value: "16200000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.75",
      Internal_Valuation_NOI: "1134000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 15 2013",
      Notes: null,
      loaded_from: null
    },
    {
      id: 461,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Place Desormeaux Holdings Inc.",
      Property_Name: "Place Desormeaux",
      Address: "",
      Postal: "",
      City: "Longueuil",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 249517,
      Lender: "First National Financial",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "23000000.00",
      First_Payment_Date: "October 1 2014",
      Term: 36,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "5.00",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "July 1 2014",
      Recent_Appraisal_Cap_Rate: "7.00",
      Recent_Appraisal_Value: "36500000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.75",
      Internal_Valuation_NOI: "2555000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "August 31 2011",
      Notes: null,
      loaded_from: null
    },
    {
      id: 462,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Plaza des Seigneurs Holdings Inc.",
      Property_Name: "Plaza des Seigneurs",
      Address: "",
      Postal: "",
      City: "Terrebonne",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 770833,
      Lender: "Otera Capital",
      Lender_Classification: "Pension Fund",
      Original_Loan_Amount: "72250000.00",
      First_Payment_Date: "March 1 2012",
      Term: 60,
      Amortization: 240,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "3.50",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2014",
      Recent_Appraisal_Cap_Rate: "6.75",
      Recent_Appraisal_Value: "4500000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.50",
      Internal_Valuation_NOI: "303750.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "February 1 2012",
      Notes: null,
      loaded_from: null
    },
    {
      id: 463,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "1605 Marcel-Laurin Inc.",
      Property_Name: "Marcel-Laurin",
      Address: "",
      Postal: "",
      City: "St Laurent (Mtl)",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 120171,
      Lender: "Sunlife",
      Lender_Classification: "Life Co.",
      Original_Loan_Amount: "22000000.00",
      First_Payment_Date: "July 1 2013",
      Term: 120,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "3.84",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "December 1 2012",
      Recent_Appraisal_Cap_Rate: "6.25",
      Recent_Appraisal_Value: "36600000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "2287500.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "May 1 2013",
      Notes: null,
      loaded_from: null
    },
    {
      id: 464,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title:
        "Centre Village et Elgar Inc; Gestion Centre Village et Elgar",
      Property_Name: "Centre Le Village",
      Address: "",
      Postal: "",
      City: "Nun's Island (Mtl)",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 96257,
      Lender: "First National Financial",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "8500000.00",
      First_Payment_Date: "January 1 2015",
      Term: 36,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "3.26",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "July 1 2014",
      Recent_Appraisal_Cap_Rate: "6.50",
      Recent_Appraisal_Value: "20900000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.25",
      Internal_Valuation_NOI: "1358500.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "December 21 2012",
      Notes: null,
      loaded_from: null
    },
    {
      id: 465,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Charter Realty (Quebec) Corp.",
      Property_Name: "Mega Centre",
      Address: "",
      Postal: "",
      City: "Montreal",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 277048,
      Lender: "First National Financial",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "27525000.00",
      First_Payment_Date: "May 1 2007",
      Term: 108,
      Amortization: 360,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "5.75",
      Pre_Payment_Penalty_Type: "Yield Maintenance ",
      Recent_Appraisal_Date: "January 1 2015",
      Recent_Appraisal_Cap_Rate: "6.25",
      Recent_Appraisal_Value: "44500000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "2781250.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 30 2007",
      Notes: null,
      loaded_from: null
    },
    {
      id: 466,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Charter Realty (Quebec) Corp.",
      Property_Name: "Mega Centre",
      Address: "",
      Postal: "",
      City: "Montreal",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 277048,
      Lender: "First National Financial",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "27525000.00",
      First_Payment_Date: "May 1 2007",
      Term: 108,
      Amortization: 360,
      Fixed_Variable: "Variable",
      BOC_Prime: "2.5",
      GOC_Prime: "0.25",
      Variable_Spread: "3.00",
      Fixed_Rate: "3.00",
      Pre_Payment_Penalty_Type: "3-Month Interest ",
      Recent_Appraisal_Date: "January 1 2015",
      Recent_Appraisal_Cap_Rate: "6.25",
      Recent_Appraisal_Value: "44500000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "2781250.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 30 2007",
      Notes: null,
      loaded_from: null
    },
    {
      id: 467,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Charter Realty (Quebec) Corp.",
      Property_Name: "Mega Centre",
      Address: "",
      Postal: "",
      City: "Montreal",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 277048,
      Lender: "First National Financial",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "27525000.00",
      First_Payment_Date: "May 1 2007",
      Term: 60,
      Amortization: 300,
      Fixed_Variable: "Variable",
      BOC_Prime: "2.5",
      GOC_Prime: "0.25",
      Variable_Spread: "3.00",
      Fixed_Rate: "3.00",
      Pre_Payment_Penalty_Type: "3-Month Interest ",
      Recent_Appraisal_Date: "January 1 2015",
      Recent_Appraisal_Cap_Rate: "6.25",
      Recent_Appraisal_Value: "44500000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "2781250.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 30 2007",
      Notes: null,
      loaded_from: null
    },
    {
      id: 468,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "Charter Realty (Quebec) Corp.",
      Property_Name: "Mega Centre",
      Address: "",
      Postal: "",
      City: "Montreal",
      Province: "QC",
      Country: "ca",
      Purchase_Price: "0.00",
      Asset_Type: "Retail",
      Asset_Class: "",
      Size: 277048,
      Lender: "First National Financial",
      Lender_Classification: "Mortgage Servicer",
      Original_Loan_Amount: "10000000.00",
      First_Payment_Date: "February 1 2012",
      Term: 60,
      Amortization: 300,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "5.00",
      Pre_Payment_Penalty_Type: "3-Month Interest ",
      Recent_Appraisal_Date: "January 1 2015",
      Recent_Appraisal_Cap_Rate: "6.25",
      Recent_Appraisal_Value: "44500000.00",
      Internal_Valuation_Date: "July 15 2015",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "2781250.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 30 2007",
      Notes: null,
      loaded_from: null
    },
    {
      id: 474,
      user_id: 1,
      Asset_Owner: "",
      Asset_Manager: "",
      Borrowing_Entity_Registered_on_Title: "123 Main Street Holdco Inc. ",
      Property_Name: "Main Street ",
      Address: "123 Main Street ",
      Postal: "zxz zxz",
      City: "Toronto",
      Province: "ON",
      Country: "ca",
      Purchase_Price: "20000000.00",
      Asset_Type: "Retail",
      Asset_Class: "Class A",
      Size: 175000,
      Lender: "Sun Life Financial",
      Lender_Classification: "Life Co.",
      Original_Loan_Amount: "15000000.00",
      First_Payment_Date: "January 31 2015",
      Term: 60,
      Amortization: 300,
      Fixed_Variable: "Variable",
      BOC_Prime: "2.75",
      GOC_Prime: "0.25",
      Variable_Spread: "0.00",
      Fixed_Rate: "3.00",
      Pre_Payment_Penalty_Type: "3-Month Interest ",
      Recent_Appraisal_Date: "January 30 2015",
      Recent_Appraisal_Cap_Rate: "6.00",
      Recent_Appraisal_Value: "3340000.00",
      Internal_Valuation_Date: "August 31 2015",
      Internal_Valuation_Cap: "5.75",
      Internal_Valuation_NOI: "200250.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "October 1 2004",
      Notes: null,
      loaded_from: null
    },
    {
      id: 497,
      user_id: 1,
      Asset_Owner: "BCIMC",
      Asset_Manager: "Bentall",
      Borrowing_Entity_Registered_on_Title: "123 ONT inc",
      Property_Name: "Voldorf mall",
      Address: "1 king street",
      Postal: "",
      City: "Regina",
      Province: "Sk",
      Country: "ca",
      Purchase_Price: "150000000.00",
      Asset_Type: "Retail",
      Asset_Class: "Class B",
      Size: 867000,
      Lender: "HSBC Bank",
      Lender_Classification: "Bank",
      Original_Loan_Amount: "110000000.00",
      First_Payment_Date: "March 10, 2016",
      Term: 60,
      Amortization: 200,
      Fixed_Variable: "Fixed",
      BOC_Prime: "",
      GOC_Prime: "",
      Variable_Spread: null,
      Fixed_Rate: "3.30",
      Pre_Payment_Penalty_Type: "",
      Recent_Appraisal_Date: "March 15, 2017",
      Recent_Appraisal_Cap_Rate: "6.00",
      Recent_Appraisal_Value: "200000000.00",
      Internal_Valuation_Date: "March 16, 2017",
      Internal_Valuation_Cap: "6.00",
      Internal_Valuation_NOI: "15000000.00",
      Equity_Surplus_Available_Possible_New_Mortgages: "70.00",
      Acquisition_Development_Date: "March 7, 2012",
      Notes: null,
      loaded_from: null
    }
  ];

  const currentYear = new Date().getFullYear();

  const newArr = sampleData.map(loan => ({
    principalRemaingAtEndOfTerm:
      amortSchedCA(
        Number(loan.Original_Loan_Amount),
        Number(loan.Fixed_Rate) || Number(loan.Variable_Spread),
        loan.Term,
        loan.Amortization
      )[loan.Term - 1]["principal remaining"] || 0,
    expiryDate: addMonths(new Date(loan.First_Payment_Date), loan.Term) // TODO: make this work correctly on edge cases!! (august 31 plus 1 month should be sep 30 !!!!!)
  }));

  const totalNumYearsForChart = 10;

  const years = [];

  for (
    let i = currentYear - totalNumYearsForChart / 2;
    i < currentYear + totalNumYearsForChart / 2;
    i++
  ) {
    years.push(i);
  }

  const numPropertiesExpiringPerYear = new Array(totalNumYearsForChart).fill(0);
  const totalPrincipalRemainingPerYear = new Array(totalNumYearsForChart).fill(
    0
  );

  newArr.forEach(loan => {
    if (years.includes(loan.expiryDate.getFullYear())) {
      numPropertiesExpiringPerYear[
        years.indexOf(loan.expiryDate.getFullYear())
      ]++;
      totalPrincipalRemainingPerYear[
        years.indexOf(loan.expiryDate.getFullYear())
      ] += loan.principalRemaingAtEndOfTerm;
    }
  });

  //   let a = 0;
  //   for (let i of totalPrincipalRemainingPerYear) {
  //     a += Number(i);
  //   }
  //   console.log(a);

  //   let b = 0;
  //   for (let i of newArr) {
  //     b += Number(i.principalRemaingAtEndOfTerm);
  //   }
  //   console.log(b);

  const data = {
    labels: years,
    datasets: [
      {
        label: "$",
        data: totalPrincipalRemainingPerYear,
        backgroundColor: "rgba(255, 99, 132, 0.5)",
        yAxisID: "1"
      },
      {
        label: "# Properties",
        data: numPropertiesExpiringPerYear,
        backgroundColor: "rgba(255, 206, 86, 0.5)",
        yAxisID: "2"
      }
    ]
  };
  const options = {
    responsive: true,
    scales: {
      yAxes: [
        {
          id: "1",
          position: "left",
          ticks: {
            beginAtZero: true
          }
        },
        {
          id: "2",
          position: "right",
          ticks: {
            beginAtZero: true
          }
        }
      ]
    }
  };

  return (
    <Fragment>
      <Bar data={data} width={2000} height={500} options={options} />
    </Fragment>
  );
}

export default LoanExpiriesPerYearChart;
